[package]
name = "sorting_evaluator"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
rand = "0.9.1"
clap = { version = "4.5.39", features = ["derive"] }
